name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  issues: write
  contents: read

jobs:
  deploy-shared:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan

      - name: Approve before apply (shared)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve shared apply"

      - run: terraform apply -auto-approve tfplan

  approve-deploy-pgadmin:
    needs: deploy-shared
    runs-on: ubuntu-latest
    steps:
      - name: Approve before pgadmin deploy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve pgadmin deploy"

  deploy-pgadmin:
    needs: approve-deploy-pgadmin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pgadmin
    env:
      TF_VAR_pgadmin_email: ${{ secrets.PGADMIN_EMAIL }}
      TF_VAR_pgadmin_password: ${{ secrets.PGADMIN_PASSWORD }}
      TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan

      - name: Approve before apply (pgadmin)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve pgadmin apply"

      - run: terraform apply -auto-approve tfplan

  approve-deploy-marquez:
    needs: deploy-pgadmin
    runs-on: ubuntu-latest
    steps:
      - name: Approve before marquez deploy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve marquez deploy"

  deploy-marquez:
    needs: approve-deploy-marquez
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marquez
    env:
      TF_VAR_marquez_db_user:     ${{ secrets.MARQUEZ_DB_USER }}
      TF_VAR_marquez_db_password: ${{ secrets.MARQUEZ_DB_PASSWORD }}
      TF_VAR_marquez_db_name:     ${{ vars.MARQUEZ_DB_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan

      - name: Approve before apply (marquez)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve marquez apply"

      - run: terraform apply -auto-approve tfplan
