name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  issues: write
  contents: read

jobs:
  # --- Shared ---
  plan-shared:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan

  approve-shared-apply:
    needs: plan-shared
    runs-on: ubuntu-latest
    steps:
      - name: Approve before apply (shared)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve shared apply"

  apply-shared:
    needs: approve-shared-apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve tfplan

  # --- PgAdmin ---
  plan-pgadmin:
    needs: apply-shared
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pgadmin
    env:
      TF_VAR_pgadmin_email: ${{ secrets.PGADMIN_EMAIL }}
      TF_VAR_pgadmin_password: ${{ secrets.PGADMIN_PASSWORD }}
      TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan

  approve-pgadmin-apply:
    needs: plan-pgadmin
    runs-on: ubuntu-latest
    steps:
      - name: Approve before apply (pgadmin)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve pgadmin apply"

  apply-pgadmin:
    needs: approve-pgadmin-apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pgadmin
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve tfplan

  # --- Marquez ---
  plan-marquez:
    needs: apply-pgadmin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marquez
    env:
      TF_VAR_marquez_db_user:     ${{ secrets.MARQUEZ_DB_USER }}
      TF_VAR_marquez_db_password: ${{ secrets.MARQUEZ_DB_PASSWORD }}
      TF_VAR_marquez_db_name:     ${{ vars.MARQUEZ_DB_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan

  approve-marquez-apply:
    needs: plan-marquez
    runs-on: ubuntu-latest
    steps:
      - name: Approve before apply (marquez)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: mostafasookar
          minimum-approvals: 1
          issue-title: "Approve marquez apply"

  apply-marquez:
    needs: approve-marquez-apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marquez
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve tfplan
